resource_group   = "cloud-demo"
location              = "East US"
virtual_network_name  = "example-network"
address_space         = ["10.0.0.0/16"]
subnet_name           = "default"
subnet_address_prefixes = ["10.0.1.0/24"]
project = "regression test"
owner = "Irfana"
duration = "20-02-2024"
