variable "location" {}
variable "RG" {}
variable "disktype" {}
variable "snapuri" {}
variable "osdisksize" {}
variable "ipname" {}
variable "ostype" {}
variable "diskname" {} 
variable "subnetname" {}
variable "vnetname" {}
variable "ip" {}
variable "vm_names" {}
variable "vm_size" {}
variable "bootdiagnostic" {}
variable "project" {}
variable "duration" {}
variable "owner" {}
variable "sql_admin" {}
variable "sql_pass" {}
variable "sqlsize" {}
variable "sqlservername" {}
variable "sqldbname" {}
variable "sqlversion" {}
variable "sku" {}
